sudo: false

language: php

php:
    - "7.0"

env:
  - COMPOSER_OPTS="--prefer-stable"

script:
  - phpunit
#  - phpunit --coverage-text --coverage-clover=coverage.clover tests/Enums/RunTest.php

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_OPTS

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

install:
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer --prefer-source install

cache:
  directories:
    - $HOME/.composer/cache
