sudo: false

language: php

php:
    - "7.0"

script:
#    - phpunit
    - phpunit --coverage-clover=build/logs/clover.xml tests/Enums/RunTest.php tests/Enums/RunTest.php

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

install:
    - alias composer=composer\ -n && composer selfupdate
    - composer validate
    - composer --prefer-source install

cache:
    directories:
        - $HOME/.composer/cache
